### PR TITLE
Update PHP Voice Reference App to use Callsign Tokens

### PR DESCRIPTION
**Pull request by ffranco-daitan**
@nadirhamid Please review and merge this whenever possible!

### CODE REVIEW

**Comment by dtolb** [comment]
@ffranco-daitan is this still valid?

**Comment by ffranco-daitan** [comment]
I think so @dtolb

**Comment by dtolb** [comment]
@ffranco-daitan do you mind just glancing over this real quick (IE just code review yourself) and I'll merge it in :)

**Comment by ffranco-daitan** [comment]
It does look good @dtolb (a.k.a. it passed self inspection) :+1:

**Pull request merged**
